#!/bin/sh
#
# backup: Defines the container backup function which should build the local cache to be backed up.

container_backup() {
 echo "[ INFO] Current directory($(PWD))"
 /bin/cp /etc/container/Corefile ./Corefile
 /bin/cp /etc/container/blacklist ./blacklist
 /bin/cp /etc/container/zone.local ./zone.local
 /bin/cp /etc/container/zone.tld ./zone.tld
 return 0
}
