version: "3.9"
services:
  coredns:
    build:
      args:
        ALPINE_VERSION: "latest"
        DASHY_VERSION: "1.9.3"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "coredns:dev"
    image: "coredns:dev"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/coredns/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/coredns/backup-volume
      
