kind: pipeline
type: exec
name: Development Build - CoreDNS

platform:
  os: linux
  arch: arm64

steps:
- name: build
  environment:
    ALPINE_VERSION: latest
    COREDNS_VERSION: 1.9.3
  commands:
  - podman build --build-arg ALPINE_VERSION=$ALPINE_VERSION --build-arg COREDNS_VERSION=$COREDNS_VERSION --format docker --file Containerfile --label revision="$(git rev-parse HEAD)" --label version="$(date +%Y.%m.%d)" --no-cache --tag coredns:drone .

- name: publish
  environment:
    CONTAINER_NAME: "coredns"
    CONTAINER_VERSION: "1.9.3"
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
  commands:
   - podman tag $CONTAINER_NAME:drone docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:$CONTAINER_VERSION
   - podman tag $CONTAINER_NAME:drone docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:latest
   - podman login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
   - podman push docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:$CONTAINER_VERSION
   - podman push docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:latest

trigger:
  branch:
  - main
