#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

app_version() {
 /usr/bin/coredns --version | head -n 1 | awk -F '-' '{print $2}'
}

## Blackhole
# /usr/bin/pgrep python3 > /dev/null
# TEST=$?
# if [ $TEST -eq 1 ] ; then
#  log "-i" "entrypoint" "Launching application - blackhole($(app_version))"
#  cd /home/blackhole
#  /usr/bin/blackhole --domains blackhole.gautier.local,blackhole.gautier.org
# fi
  
/usr/bin/update-blacklist
if [ -z "$@" ] ; then
  log "-i" "entrypoint" "Default entry"
  /usr/bin/pgrep coredns > /dev/null
  TEST=$?
  if [ $TEST -eq 1 ] ; then
   log "-i" "entrypoint" "Blocking application - coredns($(app_version))"
   /usr/bin/coredns -conf /etc/container/Corefile
  fi
  return 1
else
 log "-i" "entrypoint" "Override default($ENTRYPOINT_PARAMS)"
 log "-i" "entrypoint" "Detatched application - coredns($(app_version))"
 /usr/bin/coredns -conf /etc/container/Corefile >> /mnt/volumes/container/_log 2>&1 &
 return 0
fi
